export const energySources = [
  {
    id: 1,
    type: "Solar",
    region: "Global",
    costPerKWh: 0.12,  
    environmentalImpact: "Baixo",
    accessibility: "Alta",
    efficiency: "20%",
  },
  {
    id: 2,
    type: "Eólica",
    region: "Europe",
    costPerKWh: 0.10,  
    environmentalImpact: "Moderado",
    accessibility: "Média",
    efficiency: "35%",
  },
  {
    id: 3,
    type: "Hidráulica",
    region: "US",
    costPerKWh: 0.07,  
    environmentalImpact: "Alto",
    accessibility: "Alta",
    efficiency: "80%",
  },
  {
    id: 4,
    type: "Solar",
    region: "Brasil",
    costPerKWh: 0.15,  
    environmentalImpact: "Baixo",
    accessibility: "Alta",
    efficiency: "18%",
  },
  {
    id: 5,
    type: "Eólica",
    region: "Brasil",
    costPerKWh: 0.09,  
    environmentalImpact: "Moderado",
    accessibility: "Alta",
    efficiency: "30%",
  },
  {
    id: 6,
    type: "Hidráulica",
    region: "Brasil",
    costPerKWh: 0.05,  
    environmentalImpact: "Alto",
    accessibility: "Alta",
    efficiency: "90%",
  },
];
